@url = http://localhost:3000/transaction

###
POST {{url}}
Content-Type: application/json

{
  "description": "Supermercado",
  "value": 180.21,
  "date": "05/07/2022",
  "type": "DEBIT",
  "accountId": "62d753d43e38ac07e76f0d87",
  "categoryId": "62d751c3c684e4fc38dfcc21"
}