@url = http://localhost:3000/account

###
DELETE {{url}}/633e157c47b43690c24c4f07
Content-Type: application/json

###
GET {{url}}
Content-Type: application/json

###
POST {{url}}
Content-Type: application/json

{
  "description": "TESTE2",
  "total": 20.00
}