@url = http://localhost:3000/category

###
GET {{url}}
Content-Type: application/json

###
POST {{url}}
Content-Type: application/json

{
  "description": "Teste backend"
}

###
DELETE {{url}}/63692068c055ff44db2e251d
Content-Type: application/json