@url = http://localhost:3000/subcategory

###
GET {{url}}
Content-Type: application/json

###
POST {{url}}
Content-Type: application/json

{
  "description": "viagem",
  "categoryId": "635dca7a2b7d7c2cdc85e371"
}

###
DELETE {{url}}/636425f5337430588382b3fa
Content-Type: application/json