@url = http://localhost:3000/transaction
@accountId = 62d753d43e38ac07e76f0d87
@month = 07
@year = 2022

###
DELETE {{url}}/634ed5f3f3f24deff24efc38
Content-Type: application/json

###
GET {{url}}/account/{{accountId}}/month/{{month}}/year/{{year}}

###
POST {{url}}
Content-Type: application/json

{
  "description": "Supermercado",
  "value": 20.00,
  "date": "25/07/2022",
  "type": "DEBIT",
  "accountId": "62d753d43e38ac07e76f0d87",
  "categoryId": "62d751c3c684e4fc38dfcc21"
}

